# Generated by Django 4.2.1 on 2023-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=30)),
                ('number_pages', models.IntegerField()),
                ('author', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
