# Generated by Django 4.2 on 2023-05-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
