# Generated by Django 4.2 on 2023-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=60)),
                ('number_pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
